export const USER_SESSION_EXPIRES = 60 * 60 * 24 * 7 * 1000;

export const VERIFY_PARAMS_KEY = "VERIFY_PARAMS_KEY";
export const VERIFY_CERTIFICATE_EXPIRES = 60 * 10 * 1000;

// access
export const ANYWHY_ACCESS_KEY = "ANYWHY_ACCESS_KEY";
export const ANYWHY_ACCESS_TOTAL_KEY = "ANYWHY_ACCESS_TOTAL";
export const ANYWHY_ACCESS_DATE_KEY = "ANYWHY_ACCESS_DATE_KEY";

// KV
export const ANYWHY_KV_KEY = "ANYWHY_KV_KEY";

// uesr
export const ANYWHY_KV_USER_SESSION_KEY = "ANYWHY_KV_USER_SESSION_KEY";
export const ANYWHY_KV_USER_KEY = "ANYWHY_KV_USER_KEY";
export const ANYWHY_KV_USER_ID_KEY = "ANYWHY_KV_USER_ID_KEY";
export const ANYWHY_KV_USER_EMAIL_KEY = "ANYWHY_KV_USER_EMAIL_KEY";
export const ANYWHY_KV_USER_TOTAL = "ANYWHY_KV_USER_TOTAL";

// fake
export const ANYWHY_KV_FAKE_USER_KEY_NUM = 60;

// image
export const ANYWHY_KV_IMAGE_KEY = "ANYWHY_KV_IMAGE_KEY";
export const ANYWHY_KV_IMAGE_ID_KEY = "ANYWHY_KV_IMAGE_ID_KEY";
export const ANYWHY_KV_IMAGE_NAME_KEY = "ANYWHY_KV_IMAGE_NAME_KEY";
export const ANYWHY_KV_IMAGE_CREATEAT_KEY = "ANYWHY_KV_IMAGE_CREATEAT_KEY";
export const ANYWHY_KV_IMAGE_TOTAL_KEY = "ANYWHY_KV_IMAGE_TOTAL_KEY";
export const ANYWHY_KV_IMAGE_VIEWS_KEY = "ANYWHY_KV_IMAGE_VIEWS_KEY";
export const ANYWHY_KV_IMAGE_DOWNLOADS_KEY = "ANYWHY_KV_IMAGE_DOWNLOADS_KEY";

// blog
export const ANYWHY_BLOG_FILE_DIR_PATH = new URL("../doc/", import.meta.url);
export const ANYWHY_KV_BLOG_KEY = "ANYWHY_KV_BLOG_KEY";
export const ANYWHY_KV_BLOG_VIEWS_KEY = "ANYWHY_KV_BLOG_VIEWS_KEY";

// email limits
export const ANYWHY_EMAIL_LIMITS_COUNT_DAY = 200;
export const ANYWHY_EMAIL_LIMITS_EXPIREIN = 60 * 60 * 24;
export const ANYWHY_KV_EMAIL_LIMITS_KEY = "ANYWHY_KV_EMAIL_LIMITS_KEY";
export const ANYWHY_KV_EMAIL_LIMITS_DAY = "ANYWHY_KV_EMAIL_LIMITS_DAY";

// other
export const defaultWindow = globalThis || window;

//notify
export const ANYWHY_KV_NOTIFY_IMAGES_KEY = "ANYWHY_KV_NOTIFY_IMAGES_KEY";
export const ANYWHY_KV_NOTIFY_ID_KEY = "ANYWHY_KV_NOTIFY_ID_KEY";
